# Generated by Django 4.1.13 on 2024-05-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('stk', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
