# Generated by Django 4.1.13 on 2024-05-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
