services:
  hirex-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=order
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
