# Generated by Django 4.1.13 on 2024-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_date_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
