# Generated by Django 4.1.13 on 2024-05-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_voucher_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('freeship', 'Freeship'), ('discount', 'Discount')], max_length=100, null=True),
        ),
    ]
